### ISSUE TITLE
Error rendering

### ISSUE THREAD

**Issue by supermozzi** [edwardspec/mediawiki-extension-DownloadBook#3]
MediaWiki 1.42.1
PHP 8.2.20

When generating any book, the PDF rendering error was being reported. I analyzed the code and managed to solve the problem, but I don't know if I did it correctly.

BookRenderingTask.php file, 'startRendering' function:

--$page = WikiPage::factory( $title );
++$page = MediaWikiServices::getInstance()->getWikiPageFactory()->newFromTitle( $title );

++$localParser = MediaWikiServices::getInstance()->getParserFactory()->create();

++$popts = RequestContext::getMain()->getOutput()->parserOptions();
--$pout = $content->getParserOutput( $title, 0, $popts, true ); ++$pout = $localParser->parse(
++$content->getText(), // The content text
++$title, // The page title
++$popts // Parser options
++);

**Comment by edwardspec** [comment]
Looks correct. You can slightly simplify it by replacing
```php
MediaWikiServices::getInstance()->getParserFactory()->create()
```
with shorter
```php
MediaWikiServices::getInstance()->getParser()
```

If it works for you, can you please send a pull request?
