### ISSUE TITLE
Use automatically generated sql for schema changes

### ISSUE THREAD

**Issue by hexmode** [edwardspec/mediawiki-extension-DownloadBook#5]
See [Schema changes](https://www.mediawiki.org/wiki/Manual:Schema_changes#Automatically_generated).

**Comment by edwardspec** [comment]
Thank you for your contribution.
I've been waiting for a pull request, but now that this extension has an integration test (which passes with PostgreSQL), I went ahead and cherry-picked the commit that adds `tables.json`.

**Comment by hexmode** [comment]
Thanks, I had forgotten about this.
