### ISSUE TITLE
Newer versions broken for MediaWiki 1.39 LTS

### ISSUE THREAD

**Issue by j0hax** [edwardspec/mediawiki-extension-DownloadBook#6]
Hello, at some point the extension broke for the oldest supported version of MediaWiki.

On 2024-03-25, the latest release of the extension worked fine for a test server. This week I wanted to install the latest commit of the extension for a prod server, unfortunately something happened in the past months, as I am left with the message

>There was an error while attempting to render your book.

when using the extension.

Further information:
- Copying the old files from March to the prod server immediately fixes the issue.
- Both servers share identical configurations
- Both versions of the extension produce the required `bookrenderingtask` task in the MySQL database
- Setting, for example, `$wgDebugLogGroups['DownloadBook'] = '/tmp/downloadbook.log';` does *not* produce a debug log, it seems something goes wrong before a log can even be written.

Unfortunately, I'm not very familiar with the interior workings of MediaWiki, but I'm happy to test/provide more information upon request.

**Comment by edwardspec** [comment]
Investigating...

**Comment by edwardspec** [comment]
Should be fixed now.
I also set automated tests to run with MediaWiki 1.39 (in addition to 1.43) to avoid such problems in the future.
